// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiteWebTransactionnel.Data;

#nullable disable

namespace SiteWebTransactionnel.Migrations
{
    [DbContext(typeof(BdContexte))]
    [Migration("20260725202113_AjoutImagesProduit")]
    partial class AjoutImagesProduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiteWebTransactionnel.Models.ImageProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.Plateforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("JeuVidéoId")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JeuVidéoId");

                    b.ToTable("Plateforme");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Produit");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pour écrire et/ou dessiner (mais pas colorier).",
                            Nom = "Crayon à mine",
                            Prix = 10m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Protège très bien du soleil.",
                            Nom = "Chapeau",
                            Prix = 20m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Parfais pour clouer des clous.",
                            Nom = "Tournevis",
                            Prix = 30m
                        });
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.JeuVidéo", b =>
                {
                    b.HasBaseType("SiteWebTransactionnel.Models.Produit");

                    b.Property<string>("Développeur")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Éditeur")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("JeuVidéo");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.ImageProduit", b =>
                {
                    b.HasOne("SiteWebTransactionnel.Models.Produit", "Produit")
                        .WithMany("Images")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.Plateforme", b =>
                {
                    b.HasOne("SiteWebTransactionnel.Models.JeuVidéo", null)
                        .WithMany("Plateformes")
                        .HasForeignKey("JeuVidéoId");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.Produit", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SiteWebTransactionnel.Models.JeuVidéo", b =>
                {
                    b.Navigation("Plateformes");
                });
#pragma warning restore 612, 618
        }
    }
}
