// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiteWebTransactionnel.Data;

#nullable disable

namespace SiteWebTransactionnel.Migrations
{
    [DbContext(typeof(BdContexte))]
    partial class BdContexteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiteWebTransactionnel.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "description",
                            Nom = "nom",
                            Prix = 10m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ipsum",
                            Nom = "Lorem",
                            Prix = 20m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem",
                            Nom = "Ipsum",
                            Prix = 30m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
